CREATE TABLE client
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpf   CHAR(14)                                NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    phone CHAR(14)                                NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

ALTER TABLE client
    ADD CONSTRAINT uc_client_cpf UNIQUE (cpf);

ALTER TABLE client
    ADD CONSTRAINT uc_client_email UNIQUE (email);