CREATE TABLE rental
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id  BIGINT                                  NOT NULL,
    bike_id    BIGINT                                  NOT NULL,
    start_date date                                    NOT NULL,
    end_date   date                                    NOT NULL,
    CONSTRAINT pk_rental PRIMARY KEY (id)
);

ALTER TABLE rental
    ADD CONSTRAINT FK_RENTAL_ON_BIKE FOREIGN KEY (bike_id) REFERENCES bike (id);

ALTER TABLE rental
    ADD CONSTRAINT FK_RENTAL_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);